dist: focal

addons:
  apt:
    packages:
    - libssl-dev
    - libusb-1.0-0-dev
    - libgstreamer1.0-dev
    - gstreamer1.0-gl
    - libgstreamer-plugins-base1.0-dev
    - libgstreamer-plugins-bad1.0-dev
    - protobuf-compiler
    - libprotobuf-dev
    - libsdl1.2-dev
    - libsdl2-dev
    - libgtk-3-dev
    - libudev-dev
    - libunwind-dev
    - libtool-bin
    - libefl-all-dev

language: cpp

compiler:
  - gcc
  - clang

arch:
  - amd64
  - arm64

env:
  jobs:
    - BUILD_TYPE=Debug      CMAKE_ARGS="-DCMAKE_STAGING_PREFIX=`pwd`/staging/usr/local"
    - BUILD_TYPE=Release    CMAKE_ARGS="-DCMAKE_STAGING_PREFIX=`pwd`/staging/usr/local"
    - BUILD_TYPE=MinSizeRel CMAKE_ARGS="-DCMAKE_STAGING_PREFIX=`pwd`/staging/usr/local"
    - BUILD_TYPE=Debug \
      PATH=${TRAVIS_BUILD_DIR}/../mazda/m3-toolchain:$PATH \
      CMAKE_ARGS="-DCMAKE_TOOLCHAIN_FILE=${TRAVIS_BUILD_DIR}/../cmake/gcc-toolchain.cmake \
                  -DBUILD_MAZDA=ON -DCMAKE_STAGING_PREFIX=`pwd`/staging/usr/local"
    - BUILD_TYPE=Release \
      PATH=${TRAVIS_BUILD_DIR}/../mazda/m3-toolchain:$PATH \
      CMAKE_ARGS="-DCMAKE_TOOLCHAIN_FILE=${TRAVIS_BUILD_DIR}/../cmake/gcc-toolchain.cmake \
                  -DBUILD_MAZDA=ON -DCMAKE_STAGING_PREFIX=`pwd`/staging/usr/local"
    - BUILD_TYPE=MinSizeRel \
      PATH=${TRAVIS_BUILD_DIR}/../mazda/m3-toolchain:$PATH \
      CMAKE_ARGS="-DCMAKE_TOOLCHAIN_FILE=${TRAVIS_BUILD_DIR}/../cmake/gcc-toolchain.cmake \
                  -DBUILD_MAZDA=ON -DCMAKE_STAGING_PREFIX=`pwd`/staging/usr/local"

script:
  - env
  - cd ${TRAVIS_BUILD_DIR}
  - mkdir build && cd build
  - cmake .. -DCMAKE_BUILD_TYPE=${BUILD_TYPE} ${CMAKE_ARGS}
  - make install -j
